version: "3.8"

services:
  nginx:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/hosts:/etc/nginx/conf.d
      - /Users/maikeldorta/Code:/apps


  app-laravel:
    build:
      context: ./dockerfiles
      dockerfile: php8.dockerfile
    volumes:
      - /Users/maikeldorta/Code:/apps
    depends_on:
      - mysql
      - nginx

  mysql:
    platform: linux/arm64/v8
    image: mysql:8
    ports:
      - "3306:3306"
    env_file:
      - ./env/mysql.env
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
